name: GitHub Actions Demo
on: [push]
jobs:
 cypress-run:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
